#!/usr/bin/env zsh
#
# sway init
#
# Clean up any lingering environment variables from a previous session and
# start a new Plasma session.
#

source "${HOME}/lib/session-vars.sh"
systemctl --user unset-environment "${SESSION_VARS[@]}"
/usr/lib64/libexec/startplasma-waylandsession
