#!/usr/bin/env zsh

INHIBITOR_FILE="${XDG_RUNTIME_DIR}/screensaver.inhibit"

inhibit() {
    touch "$INHIBITOR_FILE"
}

reset() {
    rm -f "$INHIBITOR_FILE"
}

toggle() {
    if [[ -f "$INHIBITOR_FILE" ]]; then
        reset
    else
        inhibit
    fi
}

case "$1" in
    'inhibit')
        inhibit
        ;;

    'toggle')
        toggle
        ;;

    'reset')
        reset
        ;;

    *)
        print "Unhandled argument '$1'" >&2
        exit 1
        ;;
esac
