#!/usr/bin/env zsh

source "$(dirname "$0")/lib.zsh" "$0"

if get_state > /dev/null; then
    iostat="$(zpool iostat -Hpy 1 1)"
else
    iostat="$(zpool iostat -Hp 1 1)"
fi

pools="$(wc -l <<< "$iostat")"

while read pool alloc free readop writeop readb writeb rest; do
    ops="$(format_number $((readop / 1000.0)))↑ $(format_number $((writeop / 1000.0)))↓"

    if (( pools > 1 )); then
        segment "$(fontawesome '') ${pool} ${ops}"
    else
        segment "$(fontawesome '') ${ops}"
    fi
done <<< "$iostat"

set_state 'running'
