#!/usr/bin/env zsh

SELF="$0"
source "$(dirname "$(readlink -f "$SELF")")/lib.zsh" "$SELF"

if get_state > /dev/null; then
    sleep 1
else
    set_state 1
fi

read load rest < /proc/loadavg
first_segment "$(fontawesome "\uf233") ${load}"
