#!/usr/bin/env ruby

require 'status'

widgets = [
  LoadStatus.new,
  PowerStatus.new,
  NetworkStatus.new,
  AudioStatus.new,
  BacklightStatus.new,
  ScreensaverStatus.new,
  VpnStatus.new,
]

threads = widgets.map { |widget| Thread.new { widget.monitor } }
threads.each(&:join)
