#!/usr/bin/env zsh

source "$(dirname "$0")/lib.zsh" "$0"

if get_state > /dev/null; then
    (timeout 5 nmcli monitor & print -n "$! ") | while read pid rest; do
        kill "$pid"
    done
fi

nmcli -terse device status | head -1 | IFS=: read device type devstate connection rest

if [[ $type == 'wifi' ]]; then
    icon="$(fontawesome "\uf1eb")"

    case "$devstate" in
        'connected')
            signal="$(iw dev "$device" link | awk '/signal:/ { print $2 $3 }')"
            segment "${icon} ${signal}"
            ;;

        'connecting'*)
            segment "${icon} ..."
            ;;

        *)
            ;;
    esac
fi

nmcli -terse connection show --active | while IFS=: read name uuid type device rest; do
    if [[ $type == 'vpn' ]]; then
        segment "$(fontawesome "\uf023") ${name}"
    fi
done

set_state 1
