#!/usr/bin/env zsh

SELF="$0"
source "$(dirname "$(readlink -f "$SELF")")/lib.zsh" "$SELF"

main() {
    local action
    local state="$(get_state)"

    if [[ $state == 'off' ]]; then
        action="$(timeout 60 "$SELF" wait)"
    else
        action="$(get_event)"
    fi

    case "$action" in
        'reset')
            state='on'
            ;;

        'toggle')
            [[ $state == 'off' ]] && state='on' || state='off'
            ;;

        *) # timeout
            [[ $state == 'off' ]] && qdbus org.freedesktop.ScreenSaver /org/freedesktop/ScreenSaver org.freedesktop.ScreenSaver.SimulateUserActivity
            ;;
    esac

    if [[ $state == 'off' ]]; then
        segment "$(fontawesome "\uf108")"
    fi

    set_state "$state"
}

case "$1" in
    'monitor')
        start_monitor_loop sleep inf
        ;;

    'wait')
        get_event
        ;;

    'toggle')
        send_event 'toggle'
        ;;

    'reset')
        send_event 'reset'
        ;;

    *)
        main
        ;;
esac
