#!/usr/bin/env zsh

SELF="$0"
source "$(dirname "$(readlink -f "$SELF")")/lib.zsh" "$SELF"

main() {
    local action prev_state state

    action="$(timeout 60 "$SELF" wait)"
    prev_state="$(get_state)"
    state="$prev_state"

    case "$action" in
        'reset')
            state='on'
            ;;

        'toggle')
            [[ $state == 'off' ]] && state='on' || state='off'
            ;;

        *) # timeout
            [[ $state == 'off' ]] && qdbus org.freedesktop.ScreenSaver /org/freedesktop/ScreenSaver org.freedesktop.ScreenSaver.SimulateUserActivity
            ;;
    esac

    if [[ $state == 'off' ]]; then
        segment "$(fontawesome "\uf108")"
    fi

    if [[ $state != $prev_state ]]; then
        set_state "$state"
    fi
}

case "$1" in
    'monitor')
        start_monitor_loop sleep inf
        ;;

    'wait')
        get_event
        ;;

    'toggle')
        send_event 'toggle'
        ;;

    'reset')
        send_event 'reset'
        ;;

    *)
        main
        ;;
esac
