#!/usr/bin/env zsh

SELF="$0"
source "$(dirname "$(readlink -f "$SELF")")/lib.zsh" "$SELF"

main() {
    if get_state > /dev/null; then
        get_event > /dev/null
    fi

    if nmcli --terse --fields type,state connection show | grep -q 'vpn:activated'; then
        segment "$(fontawesome "\uf023")"
    fi

    set_state 1
}

case "$1" in
    'monitor')
        start_monitor_loop nmcli connection monitor
        ;;

    *)
        main
        ;;
esac
