#!/usr/bin/env zsh

SELF="$0"
source "$(dirname "$(readlink -f "$SELF")")/lib.zsh" "$SELF"

refresh() {
    if get_state > /dev/null; then
        timeout 60 "$SELF" wait
    else
        set_state 1
    fi

    if nmcli --terse --fields type,state connection show | grep -q 'vpn:activated'; then
        segment "$(fontawesome "\uf023")"
    fi
}

case "$1" in
    'monitor')
        start_monitor_loop nmcli connection monitor
        ;;

    'wait')
        get_event > /dev/null
        ;;

    *)
        refresh
        ;;
esac
