#!/usr/bin/env -S pdeathsig zsh

if [[ $# != 1 ]]; then
    print "Usage: ${0} WSNUM" >&2
    exit 1
fi

FIFO="/tmp/status-${UID}/sway-workspace-${1}.fifo"

while :; do
    if [[ -p "$FIFO" ]]; then
        read -re < "$FIFO"
    else
        sleep 1
    fi
done
